version: '3.7'
services:
  fuseki:
    image: stain/jena-fuseki:3.13.1
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      - /data/fuseki:/fuseki
    env_file:
      - ./fuseki.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "fuseki-log"
  yasgui:
    image: erikap/yasgui
    container_name: yasgui
    ports:
      - "3040:80"
    env_file:
      - ./yasgui.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "yasgui-log"
    depends_on:
      - fuseki
  kg-api:
    image: tbfy/kg-api:0.1
    container_name: kg-api
    ports:
      - "7777:7777"
    env_file:
      - ./kg-api.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "kg-api-log"
    depends_on:
      - fuseki
#  kg-ingestion-service:
#    image: tbfy/kg-ingestion-service
#    container_name: kg-ingestion-service
#    volumes:
#      - /data/ingestion:/ingestion
#    env_file:
#      - ./kg-ingestion-service.env
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"
#        labels: "kg-ingestion-service-log"
#    depends_on:
#      - fuseki
