index.html: tbfy-ontology.rdf extraction.xsl
	transform -xsl:extraction.xsl -s:tbfy-ontology.rdf -o:index.html

#tbfy-ontology.rdf: ../model/tbfy-ontology.ttl
#	riot --output=rdfxml ../model/tbfy-ontology.ttl > tbfy-ontology.rdf
